### ISSUE TITLE
random idea refresher

### ISSUE THREAD

**Issue by ajschumacher** [ajschumacher/ajschumacher.github.io#164]
some way of showing you a sample of your own ideas, things to think about, quotes, etc.

**Comment by ajschumacher** [comment]
could use this!

https://api.github.com/repos/ajschumacher/ajschumacher.github.io/issues?state=open

**Comment by ajschumacher** [comment]
&per_page=100

**Comment by ajschumacher** [comment]
https://developer.github.com/v3/#pagination

**Comment by yoursunny** [comment]
You could use `fetch` instead of `XMLHttpRequest`. `fetch` is easier to use because it's Promise_based.
