### ISSUE TITLE
Malwarebytes blocking planspace[dot]org due to Trojan

### ISSUE THREAD

**Issue by vicsjoo** [ajschumacher/ajschumacher.github.io#299]
-Blocked Website Details-
Malicious Website: 1
, C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe, Blocked, -1, -1, 0.0.0, , 

-Website Data-
Category: Trojan
Domain: planspace.org
IP Address: 172.67.220.36
Port: 443
Type: Outbound
File: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

(end)

**Comment by ajschumacher** [comment]
@vicsjoo what is this? Can you tell me more? Is there something I can/should do?

**Comment by ajschumacher** [comment]
I posted on the malwarebytes forum; maybe that's the thing to do? https://forums.malwarebytes.com/topic/280038-planspaceorg-false-positive/

**Comment by ajschumacher** [comment]
They say the block will be removed! 😄

**Comment by vicsjoo** [comment]
Yes, you did the right thing, the block was removed 😄

**Comment by ajschumacher** [comment]
@vicsjoo thanks for letting me know about the issue!
