### ISSUE TITLE
add mathjax support!

### ISSUE THREAD

**Issue by ajschumacher** [ajschumacher/ajschumacher.github.io#56]

**Comment by ajschumacher** [comment]
hmm yeah that way sucked

**Comment by johnosaurus-rex** [comment]
What happened?

**Comment by ajschumacher** [comment]
I want to display LaTeX math on my blog.

**Comment by ajschumacher** [comment]
I set it up a way, but it kind of sucked.

**Comment by ajschumacher** [comment]
I think there's a nicer way.

**Comment by ajschumacher** [comment]
I think I'm going to do it like this: http://christopherpoole.github.io/using-mathjax-on-github-pages/

And then just switch over all my old wordpress-style "$latex x^2$" stuff.

Sound good, @johnosaurus-rex?

**Comment by johnosaurus-rex** [comment]
Sounds great. Also, I have feedback on your merging data speech. We'll talk
soon.

**Comment by ajschumacher** [comment]
Cool, thanks! What feedback?

**Comment by johnosaurus-rex** [comment]
I liked it. Positive feedback

**Comment by ajschumacher** [comment]
Thanks! Anything else? I'm giving a version of that talk again a week from tomorrow at the Open Data Science Conference in Boston.

**Comment by johnosaurus-rex** [comment]
I would give you better notes, but I'm out and about at the moment

**Comment by ajschumacher** [comment]
haha okay - looking forward to it!
